steps:
  # Deploy ke App Engine (Menambahkan --quiet)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    args: ['gcloud', 'app', 'deploy', 'app.yaml', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY