steps:
  # Deploy ke App Engine (Menambahkan dir: 'frontend')
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    args: ['gcloud', 'app', 'deploy', 'app.yaml']

# TAMBAHKAN INI DI PALING BAWAH:
options:
  logging: CLOUD_LOGGING_ONLY